### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by iiijarvis** [haijungu/nodejs-alipay-api#1]
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\迅雷下载\nodejs-alipay-api-master\routes\index.js:13:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
想请问这个是什么问题？
没有假如moment模块

**Comment by iiijarvis** [comment]
怎么没有原理和运行介绍？

这个我写着玩的 ， 就是调一下支付宝的接口
